name: flutter_spotify_bootleg
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.4.2
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.7
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  flutter_lints: ^5.0.0
  freezed: ^2.5.8

flutter:
  uses-material-design: true